FROM python:3.12-slim

WORKDIR /web

COPY ./docker/requirements.txt requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libc-dev \
    locales \
    locales-all \
    git \
    curl \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

RUN locale-gen cs_CZ.utf8

RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN python -m pip install --upgrade pip
RUN pip install uv
RUN uv pip install --no-cache-dir -r requirements.txt

ENV LC_ALL cs_CZ.utf8
ENV LANG cs_CZ.utf8
ENV LANGUAGE cs_CZ.utf8

COPY . .

EXPOSE 5099
